services:
  # Redis service for BullMQ queue
  redis:
    image: redis:7-alpine
    container_name: swstarter-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - swstarter-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend service
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
      target: backend-production
    image: swstarter-backend:latest
    container_name: swstarter-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - swstarter-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
      target: frontend-production
      args:
        VITE_API_BASE_URL: http://localhost:3000/api
    image: swstarter-frontend:latest
    container_name: swstarter-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - swstarter-network
    restart: unless-stopped

networks:
  swstarter-network:
    driver: bridge

volumes:
  # Optional: for persistent data if needed
  shared-data:
  redis-data:
